#!/bin/bash

NAME="pbtitle"
VERSION="0.002"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-12-25"
UPDATED="2018-03-30"

prestr="%{A1:polybar-msg hook pbtitle TRGHOOK:}"
prestr+="%{A2:i3run -c Conky -e conky && i3fyra -z ABD:}"
sufstr="%{A}%{A}"

main(){
  while getopts :vhr option; do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  event="$1"

  mode=$(i3var get pbtitlemode)

  [[ $event != color ]] && { 

    alst=($(i3list))

    VIS=${alst[1]}
    AWC=${alst[7]}
    AWW=${alst[8]}
    AWX=${alst[45]}
    AWY=${alst[46]}
    AWD=${alst[47]}
    AWH=${alst[48]}
    WSF=${alst[44]}

    OFS=${IFS}
    IFS=$'\n'
    tit=($(i3get -r cit))
    IFS="${OFS}" 
  }

  case "$event" in
    advanced ) [[ $mode != advanced ]] \
      && i3var set pbtitlemode advanced && mode="advanced" ;;

    color ) [[ $mode != color ]] \
      && i3var set pbtitlemode color && mode="color"       ;;

    normal ) [[ $mode != normal ]] \
      && i3var set pbtitlemode normal && mode="normal"     ;;

    title )
      if [[ ${tit[0]} = Thunar ]] && [[ ${tit[1]} != "filemanager_b" ]]; then
        ttl="${tit[2]%' - File Manager'*}"
        ttl="${ttl/$HOME/'~'}"
        ttl="${ttl//'"'/}"
        i3-msg -q title_format "$ttl"
        gotofolder "${ttl}"
      fi
    ;;
  esac

  case "$mode" in
    color ) 
      colorarray=($(xrdb -query | awk '
        $1 ~ /\*\.color.*:/ {
          c=$1
          sub(/\*\.color/,"",c)
          sub(/:/,"",c)
          ac[c]=$2
          if(c==9){exit}
        }

        END{
          for(c in ac){
            print ac[c]
          }
        }
      '))

      prestr=${prestr/TRGHOOK/"3"}
      echo -n "${prestr}"

      for color in "${!colorarray[@]}"; do
        act='echo -n \'"${colorarray[$color]^^}"' | xclip -selection clipboard :}'
        bg="%{B${colorarray[$color]}}"
        [[ ${color} =~ 7|15|14 ]] \
          && fg="%{F${colorarray[8]}}" \
          || fg="%{F${colorarray[7]}}"
        [[ ${#color} -eq 1 ]] && str=" 0${color} " || str=" ${color} "
        echo -n "%{A3:${act}${fg}${bg}${str}%{B-}%{F-}%{A} "
      done

      echo -n "${sufstr}"
     
      i3var set pbtitlemode colour
    ;;
    advanced ) 
      # [[ ! $event =~ focus ]] && exit
      prestr=${prestr/TRGHOOK/"5"}
      act1='echo -n \'"$AWX $AWY $AWD $AWH"' | xclip -selection clipboard :}'
      act2='echo -n \'"${tit[0]}"' | xclip -selection clipboard :}'
      act3='echo -n \'"${tit[1]}"' | xclip -selection clipboard :}'
      advt="%{A3:${act1}$AWX $AWY $AWD $AWH%{A} "
      advt+="%{A3:${act2}${tit[0]}%{A} "
      advt+="%{A3:${act3}${tit[1]}%{A}"
      newtitle "${advt}" "1"
    ;;
    colour ) ;;
    normal )  
      prestr=${prestr/TRGHOOK/"4"}
      if [[ ${tit[0]} = Conky ]]; then
        newtitle "" "0"
      elif [[ $AWW != $WSF ]]; then
        newtitle "$(i3get -r t)" "1"

      # if i34ws && titlemod!=rice && AWC=A : A.title white
      elif [[ $AWC = ${I3FYRA_MAIN_CONTAINER} ]]; then
        tit="$(i3get -r t)"
        i3var set oldtitle "${tit//[\"]/}"
        newtitle "${tit}" "1"
        # i3var set oldtitle

      # if i34we && titlemod!=rice && AWC!=A : oldtitle grey
      else
        newtitle "$(i3var get oldtitle)" "0"
      fi
  esac
}

# hook-2 = pbtitle normal
# hook-3 = pbtitle advanced
# hook-4 = pbtitle color
# hook-5 = pbtitle taskbar



newtitle(){
  local ttl="$1"
  local col

  case $2 in
    1   ) col=$(xrdb -query | awk '/mondo.colors.act2:/ {print $2}') ;;
    0|* ) col=$(xrdb -query | awk '/mondo.colors.act3:/ {print $2}') ;;
  esac
  

  echo -n "${prestr}"
  echo -n "%{F${col}}${ttl//[\"\\]}%{F-}"
  echo -n "${sufstr}"
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="1"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}


bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

polybar(1), polybar-msg(1)
"

about='
`pbtitle` - Short description

SYNOPSIS
--------

`pbtitle` [`-v`|`-h`] *EVENT*

DESCRIPTION
-----------

`pbtitle` is intended to be used as output in a 
statusbar. Different output is displayed depending 
on the *EVENT*.


| **EVENT** | **OUTPUT**
|:----------|:-----------------------------------
| advanced  | Class and instance of active window
| normal    | Title of active window
| color     | 16 colors defined in .xresources
| focus     | –
| title     | –

When rightc licked objects will be put into the 
*ClipBoard*

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.


FILES
-----
*~/.config/polybar/config*  
Polybar configuration file.

DEPENDENCIES
------------

polybar  
i3var  
i3get  
i3list  
xrdb  
xclip  
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
