#!/bin/bash

NAME="pbweather"
VERSION="0.001"
AUTHOR="unknown"
CONTACT=''
CREATED="2017-12-19"
UPDATED="2017-12-19"

# Based on http://openweathermap.org/current

# weatherinfo file should contain these variables, city ID and API key
# can be aquired at: http://openweathermap.org/find

# API_KEY="KEY"
# CITY_ID="ID" 

source "$HOME/tmp/weatherinfo"

main(){
  while getopts :vh option; do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  URGENT_LOWER=0
  URGENT_HIGHER=30

  ICON_SUNNY=""
  ICON_CLOUDY=""
  ICON_RAINY=""
  ICON_STORM=""
  ICON_SNOW=""
  ICON_FOG=""

  SYMBOL_CELSIUS=""
  # SYMBOL_CELSIUS="℃"

  WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
  WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
  WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
  WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

  if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
    echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
    echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
    echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
    echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
    echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  else
    echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  fi

  if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
    exit 33
  fi
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

polybar(1)
"

about='
`pbweather` - Prints weather information

SYNOPSIS
--------

`pbweather` [`-v`|`-h`]

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
