#!/bin/bash

NAME="pbmedia"
VERSION="0.006"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-12-31"
UPDATED="2018-04-11"

main(){
  while getopts :vhm: option; do
    case "${option}" in
      
      (m) mode=${OPTARG} 
          shift $((--OPTIND)) ;;

      (v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      (h|*) printinfo && exit ;;
    esac
  done

  action="$1"

  mode=${mode:-$(getmode)}
  
  if [[ $mode = mpv ]];then
    mpvt=$(i3get -c mpv -r t)
    op="${mpvt%.*}"
    op=${op//\'/}
    op=${op//\"/}
    # mpc -q pause
  else
    op=$(mpdstatus)
  fi

  case "$action" in
    (start) 
      echo "${op}"
      [[ -z $(pidof -x mpclisten) ]] \
        && mpclisten > /dev/null 2>&1 &
    ;;
    (update)
      echo "${op}"
    ;;
    (resume)
      echo ""
      [[ -z $(pidof -x mpclisten) ]] \
        && mpclisten > /dev/null 2>&1 &
    ;;
    
  esac
}

getmode(){
  declare -A aCork

  eval "$(pactl list | awk '
    $1=="Corked:" {cfound=1;curcork=$2}
    cfound==1 && $1=="application.icon_name" {
      gsub("[\"]","",$3)
      print "aCork[" $3 "]=" curcork
      cfound=0
    }')"

  mode=mpd
  
  if [[ ${aCork[mpv]} = yes ]] && [[ ${aCork[mpd]} != no ]]; then
    for id in $(i3viswiz -p c | tail +3 | awk '{print $NF}'); do
      if [[ $id = mpv ]]; then
        mode=mpv
        break
      fi
    done
  elif [[ ${aCork[mpv]} = no ]]; then
    mode=mpv
  fi

  echo $mode
}

mpdstatus(){
  local op

  OFS=${IFS}
  IFS=$'\n'
  minf=($(mpc current -f "%file%\n%title%\n%artist%\n%album%"))
  IFS="${OFS}"

  fp="${minf[0]}"
  fld=${fp%%/*}
  fnm=${fp##*/}
  ttl=${minf[1]}
  art=${minf[2]}
  alb=${minf[3]}

  op=""
  if [[ $fld = pod ]]; then
    op=${fnm%%.*}
  elif [[ $fld = y ]]; then
    op=${fnm%.*}
    [[ $op =~ 'Lunduke Show' ]] && op=${op##*\' - }
    op=${op//\'/}
    op=${op/' (Audio)'/}
    op=${op/' [Official Audio]'/}
    op=${op/' (Official Audio)'/}
    op=${op/' (Full Album'.*')'/}
    op=${op/' (Full Album)'/}
    op=${op/' (full album)'/}
    op=${op/' (OFFICIAL VIDEO'?*')'/}
    op=${op/' (OFFICIAL VIDEO)'/}
    op=${op/' Official Video'/}
    op=${op/' (Official '.*')'/}
    op=${op/' [Audio'.*']'/}
    op=${op/' ('????') Full Album'/}
    op=${op/' ('?*' Full Album)'/}
    op=${op/' ('????') (Full '?*')'/}
    op=${op%' @ '*}
  elif [[ -n $ttl ]]; then
    [[ -n $art ]] && op="${art} - "
    op+="${ttl}"
  else
    # op=${fld}
    op=${fnm%.*}
  fi

  sts=$(mpc|awk 'NR==2{gsub("[[]|[]]","",$1);print $1;exit}')

  if [[ $sts = paused ]]; then
    col=$(xrdb -query | awk '/mondo.colors.act3:/ {print $2}') 
    op="%{F${col}}${op}%{F-}"
  fi 
  
  op=${op:-"turn on some music"}

  echo "$op"
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

bar(1), foo(5), xyzzy(1), [Linux Man Page Howto](
http://www.schweikhardt.net/man_page_howto.html)
"

about='
`pbmedia` - Displays the filename of the currently active media file.

SYNOPSIS
--------

`pbmedia` [`-v`|`-h`]

DESCRIPTION
-----------

`pbmedia` Prints the filename of the currently 
playing media file in `mpd` or `mpv`. And applies
some string and color formatting depending on the
state and path of the file.

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.


DEPENDENCIES
------------

i3viswiz  
i3get  
mpd  
mpc  
mpv  
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
