#!/bin/bash

NAME="i3off"
VERSION="0.02"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-29"
UPDATED="2017-12-17"

cleanup(){
  [[ -n $(i3get -i "sublime_notes") ]] \
    && i3-msg "[instance=sublime_notes]" kill
  pidof mpd && killall mpd
  pidof cairo-dock && killall cairo-dock
  pidof qbittorrent && killall qbittorrent
  pidof polybar && killall polybar
  
  while [[ -n $(i3get -i "sublime_notes") ]]; do sleep .2; done
  i3-msg "[instance=sublime_main]" kill
}

main(){
  while getopts :vhxdr option; do
    case "${option}" in
      x) ACTION='i3-msg exit' ;;
      d) ACTION='sudo shutdown now' ;;
      r) ACTION='sudo reboot now' ;;

      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  cleanup
  ${ACTION}
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

i3(1)
"

about='
`i3off` - Cleanup before exiting i3

SYNOPSIS
--------

`i3off` [`-v`|`-h`|`-r`|`-d`|`-x`]

DESCRIPTION
-----------

This script runs the `cleanup()` function before 
exiting `i3`.

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.

`-x`
  Exits i3 and xorg.

`-r`
  reboot.

`-d`
  shutdown.
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
