#!/bin/bash

NAME="fmb"
VERSION="0.003"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-12-19"
UPDATED="2018-04-01"

FMB_INSTANCE=${FMB_INSTANCE:-'filemanager_b'}
FMB_TARGET="i3get -i thunar -r d -y"

command=$(cat << EOF
xfconf-query --channel thunar --property /last-view --set ThunarDetailsView \
&& xfconf-query --channel thunar --property /last-show-hidden --set false \
&& xfconf-query --channel thunar --property /last-sort-column --set THUNAR_COLUMN_NAME \
&& xfconf-query --channel thunar --property /last-sort-order --set GTK_SORT_ASCENDING \
&& xfconf-query --channel thunar --property /last-icon-view-zoom-level --set THUNAR_ZOOM_LEVEL_SMALL \
&& xfconf-query --channel thunar --property /last-details-view-fixed-columns --set true \
&& xfconf-query --channel thunar --property /last-details-view-zoom-level --set THUNAR_ZOOM_LEVEL_SMALLEST \
&& xfconf-query --channel thunar --property /last-details-view-column-order --set THUNAR_COLUMN_NAME,THUNAR_COLUMN_SIZE,THUNAR_COLUMN_TYPE,THUNAR_COLUMN_DATE_MODIFIED \
&& xfconf-query --channel thunar --property /last-details-view-visible-columns --set THUNAR_COLUMN_DATE_MODIFIED,THUNAR_COLUMN_NAME \
&& xfconf-query --channel thunar --property /last-details-view-column-widths --set 50,172,50,50,274,50,50,92,468 \
&& thunar & xdotool set_window --classname "$FMB_INSTANCE" \`${FMB_TARGET}\`
EOF
)

main(){
  while getopts :vhli: option; do
    case "${option}" in
      i) FMB_INSTANCE="${OPTARG}" ;;
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

i3run -i "$FMB_INSTANCE" -e "${command}"

}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

i3run(1), xdotool(1), thunar(1)
"

about='
`fmb` - Run or raise a `plain notes` sublime instance.

SYNOPSIS
--------

`fmb` [`-v`|`-h`|] [`-i` *FMB_INSTANCE*]

DESCRIPTION
-----------

This command is just a shortcut to a complex command
used to run or raise a `thunar` instance with a special
instance name and settings applied.

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.

`-i` *FMB_INSTANCE*  
  Instance name to give the filemanager window.
  Defautlt: *filemanager_b*

ENVIRONMENT
-----------

`FMB_INSTANCE`
  If non-null rename instance name of filemanager
  window. Overridden by the `-i` option.
  Defautlt: *filemanager_b*

DEPENDENCIES
------------

i3run
xdotool
thunar
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
