#!/bin/bash

NAME="starttimer"
VERSION="0.003"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-12-31"
UPDATED="2018-04-02"

main(){
  while getopts :vh option; do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  declare -i milli sec min hour minutes
  min=0
  minutes=0
  seconds=0
  timer=$(date +%s%N | cut -b1-13)
  while :; do
    milli=$(($(date +%s%N | cut -b1-13) - $timer))
    seconds=$((milli/1000))
    sec=$(( seconds-(minutes*60) ))
    ((sec>59)) && ((++min)) && ((++minutes)) && sec=0
    ((min>59)) && ((++hour)) && min=0
    if [[ $sec != $oldsec ]]; then
      tajm=$(printf '%02d:%02d:%02d' "$hour" "$min" "$sec") 
      # > /tmp/pbrectime
      case $((minutes<22?1:minutes>45?3:2)) in
        (1) echo "${tajm}" > /tmp/pbrectime ;;
        (2) 
          acol="$(xrdb -query | awk '/\*color0:/ {print $2}')"
          echo "%{B${acol}}${tajm}%{B-}" > /tmp/pbrectime 
        ;;
        (3) 
          acol="$(xrdb -query | awk '/\*color1:/ {print $2}')"
          echo "%{B${acol}}${tajm}%{B-}" > /tmp/pbrectime 
        ;;
      esac
      oldsec=$sec
      polybar-msg hook pbrectime 2
    fi
    sleep .5
    [[ ! -f /tmp/pbrectime ]] \
      && sleep .5 && polybar-msg hook pbrectime 3 && break
  done

}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

bar(1), foo(5), xyzzy(1), [Linux Man Page Howto](
http://www.schweikhardt.net/man_page_howto.html)
"

about='
`starttimer` - Short description

SYNOPSIS
--------

`starttimer` [`-v`|`-h`] [`-c` *config-file*] *file* ...

DESCRIPTION
-----------

`starttimer` frobnicates the bar library by tweaking internal symbol tables. By
default it parses all baz segments and rearranges them in reverse order by
time for the xyzzy(1) linker to find them. The symdef entry is then compressed
using the WBG (Whiz-Bang-Gizmo) algorithm. All files are processed in the
order specified.

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.

`-c` *config-file*
  Use the alternate system wide *config-file* instead of */etc/foo.conf*. This
  overrides any `FOOCONF` environment variable.


FILES
-----

*/etc/foo.conf*
  The system wide configuration file. See foo(5) for further details.

*~/.foorc*
  Per user configuration file. See foo(5) for further details.

ENVIRONMENT
-----------

`FOOCONF`
  If non-null the full pathname for an alternate system wide */etc/foo.conf*.
  Overridden by the `-c` option.

DEPENDENCIES
------------

go-md2man
i3get
Sublime Text
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
