#! /bin/env bash
pas=($(ponymix list | awk '\
  $3~/alsa_input.usb*/{found=1}
  found==1 && $2=="Volume:" {
    gsub("[%]","",$3)
    gsub("[[]|[]]","",$4)
    print $3 " " $4
    exit
  }
'))

blk="$(xrdb -query | awk '/\*color0:/ {print $2}')"
wht="$(xrdb -query | awk '/\*color7:/ {print $2}')"

[[ ${pas[1]} != Muted ]] \
  && echo "%{F${blk}} ${pas[0]}%{F-}" \
  || echo "%{F${wht}} ${pas[0]}%{F-}"
