#!/bin/bash

# This script is executed every time a theme is generated.
# Each generator can have it's own mondo-generate script.

# The default syntax is bash, but by changing the shebang,
# one could use another language (f.i. perl or python).

# $1 is equal to: $MONDO_DIR/generator/TYPE/THEME[.extensions]

# If this script is not needed, this file can safely be removed.
# (removing the file, will improve executioni speed)

this_dir="${1%/*}"
this_file="${1##*/}"
this_theme="${this_file%.*}"

# To source the settings file one could use this:
source "${this_dir}/mondo-settings"

mv -f "$1" "$themes_dir"
ln "$themes_dir/$this_file" "$1" 

cat "$twoface_file" | head -n -1 > /tmp/sublt
echo "
  \"$this_theme\": {
    \"color_scheme\": \"Packages/User/Color Highlighter/themes/$this_file\"
  },
}" >> /tmp/sublt

mv -f /tmp/sublt "${twoface_file}"

