#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# for f in "$HOME/.bash/"*; do
#     source "$f"
# done

# unset f

. "$HOME/.bash/alias"
. "$HOME/.bash/prompt"
. "$HOME/.bash/export"
. "$HOME/.bash/path"

if [[ -z $DISPLAY ]]; then

  # wait two seconds for input from user
  # start desired environment.
  # if none selected, defaults to startx (i3)

  read -rsn1 -t1 input
  if [ -n "$input" ]; then
    case $input in
      1 ) start=bash ;; # bash
      2 ) startx > /dev/null 2>&1 ;;
      # 3 ) sudo systemctl start lightdm.service > /dev/null 2>&1 ;;
    esac
  fi

  [ -z "$input" ] && startx > /dev/null 2>&1
  
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] \
  && source "$HOME/.rvm/scripts/rvm"

GEM_HOME=$(ruby -e 'print Gem.user_dir')
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
PATH="$HOME/.gem/ruby/2.4.0/bin:$PATH"
PATH="$HOME/.rvm/bin:$PATH"
PATH="$PATH:/opt/mssql-tools/bin"

export GEM_HOME
export PATH

. "$HOME/.bash/func"



  



