#!/bin/bash

NAME="i3clone"
VERSION="0.001"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-29"
UPDATED="2017-11-29"

about="
$NAME - $VERSION - $UPDATED
created: $CREATED by $AUTHOR
*******************************
Clones the current window, the new window will
be moved to the same [i3fyra](/i3ass/i3fyra)
container. Currently only allows URxvt windows.

usage
-----
\`\$ $NAME [OPTION] ARGUMENT\`

| option | argument | function                   |
|:-------|:---------|:---------------------------|
| -v     |          | show version info and exit |
| -h     |          | show this help and exit    |

dependencies
------------
- DEPENDENCY

contact
-------
$CONTACT
"

while getopts :vh option
do
  case "${option}" in
    v) printf '%s\n' \
         "$NAME - version: $VERSION" \
         "updated: $UPDATED by $AUTHOR"
       exit ;;
    h) printf '%s\n' "${about}" && exit ;;
  esac
done

lst=($(i3list))

awc=${lst[7]}
urxvtc -name toclone &
clid=$(i3get -i toclone -y -r d)
[[ $awc != X ]] && i3fyra -m "$awc"
xdotool set_window --classname "clonedterm" "$clid"

