#!/bin/bash

# subact - perform action on currently open file in sublime
# if file is argument dont catch title from sublime
# 
# dependencies:
# -------------
# i3get
# toilet
# lolcat
# ansi2html


REM_ROOT="${HOME}/www"
FLD_SCRIPTS="scripts"
FLD_DOTS="dots"
LOC_SCIRPT_SRC="${HOME}/bin"

FORTUNE_OPTIONS="$HOME/etc/fortunes/budcol"
TOILET_OPTIONS='-f 3d.flf'
LOLCAT_OPTIONS='-p 10'

newpost(){
  cd ${REM_ROOT} 
  # create _index.md in all subfolders to define
  # sections properly.
  trgtmp=${trg_url%'/'*}
  echo "${trg_url}"
  while [[ -n ${trgtmp} ]]; do
    hugo new "${trgtmp}/_index.md"
    sed -i "/title/c\title: \"${trgtmp##*'/'}\"" "content/${trgtmp}/_index.md"
    sed -i "/draft/c\draft: false" "content/${trgtmp}/_index.md"
    trgtmp=${trgtmp%'/'*}
  done

  hugo new ${trg_url}.md
  # https://stackoverflow.com/a/11245501
  sed -i "/fspath/c\fspath: \"${st}\"" content/${trg_url}.md
  mkdir -p "${trg_lbd}"
  postbanner -t "${TOILET_OPTIONS}" -l "${LOLCAT_OPTIONS}" -o "${trg_lbd}/banner.html" "${fo}"
  postquote -f "${FORTUNE_OPTIONS}" "${trg_lbd}/quote.html"
}

if [[ ! -f "${1/'~'/$HOME}" ]]; then
  st=$(i3get -i sublime_text -r t)
  st=${st%' -'*}
  [[ $st =~ '(' ]] && st=${st%' ('*}
  st=${st:1}         # fullpath short
else
  st="${1}"
fi

fp=${st/'~'/$HOME} # fullpath extended
fl=${fp##*'/'}     # filename
fc=${fp//'.'/}     # path without dots
# remove extension or leading dot
[[ ${fl:0:1} = '.' ]] && fo=${fl:1} || fo=${fl%.*}
fd=${fc%'/'*}      # dir

[[ $fd = $HOME ]] && fd+='/'

if [[ $fd = $LOC_SCIRPT_SRC ]]; then 
  trg=${FLD_SCRIPTS}
  trg_mdd="${REM_ROOT}/content/${trg}"
  trg_mdf="${trg_mdd}/${fo}.md"
  trg_lbd="${REM_ROOT}/static/${trg}/${fo}"
  trg_fld="${trg_lbd}/files"
  trg_flf="${trg_fld}/${fo}"
else
  trg=${FLD_DOTS}
  trg_mdd="${REM_ROOT}/content/${trg}/${fd/${HOME}\//}"
  trg_mdf="${trg_mdd}/${fo}.md"
  trg_lbd="${REM_ROOT}/static/${trg}/${fd/${HOME}\//}/${fo}"
  trg_lbf="${trg_lbd}/banner.html"
  trg_fld="${trg_lbd}/files"
  trg_flf="${trg_fld}/${fo}"
fi

trg_url="${trg_mdd/${REM_ROOT}\/content/}/${fo}"
# backup link folder
trg_dbd="${HOME}${trg_mdd/${REM_ROOT}\/content/}"
trg_dbd="${trg_dbd/scripts/src}"
trg_dbd="${trg_dbd/dots/dot}"

# create files and links if they don't exist
[[ ! -f "${trg_mdf}" ]] && newpost
if [[ ! -f "${trg_flf}" ]];then
  mkdir -p "${trg_fld}"
  # move file from FS to DB
  mv $fp "${trg_flf}"  
  # if dot, link back to FS
  [[ ! $fd = $LOC_SCIRPT_SRC ]] && ln "${trg_flf}" $fp
  # create links to convenient folders
  mkdir -p ${trg_dbd}
  ln ${trg_flf} ${trg_dbd}/${fl}
fi

i3run -i 'sublime_text' -e subl
subl "${trg_mdf}"


