#!/bin/sh
# .xinitrc - curated by budRich

xset -b b off
xrdb -merge $HOME/.Xresources
# xrandr --output eDP-1 --auto --left-of HDMI-1 --primary &
hsetroot -tile /home/bud/etc/bitmap-walls/patterns-png/line_diag3_2.png \
  -tint "$(xrdb -query | awk '/\*background/ {print $2}')"
setxkbmap -layout seba -option lv3:ralt_switch -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'
numlockx on > /dev/null 2>&1
dunst > /dev/null 2>&1 &
# xinput set-prop 17 139 0
urxvtd -q -o -f
dropbox start &

# igi &

killall polybar
killall qbittorrent
killall mpd

compton -b > /dev/null 2>&1
sxhkd > /dev/null 2>&1 &

xbanish &
mpd > /dev/null 2>&1 &

exec i3

