#!/bin/bash

NAME="pbtog"
VERSION="0.001"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-29"
UPDATED="2017-12-17"

main(){
  while getopts :vh option; do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  pbid=$(xdotool search --onlyvisible --name "polybar-example_LVDS1")

  # no id, bar is either hidden or doesn't exit
  if [[ -z $pbid ]]; then
    pbid=$(xdotool search --name "polybar-example_LVDS1")
    [[ -n $pbid ]] && xdotool windowmap "$pbid" \
      || polybar -c "$HOME/.config/polybar/budbar" -r example 2>&1 &
  else
    xdotool windowunmap "$pbid"
  fi
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>

SEE ALSO
--------

polybar(1), xdotool(1)
"

about='
`pbtog` - Toggles visibility of polybar

SYNOPSIS
--------

`pbtog` [`-v`|`-h`]

DESCRIPTION
-----------

Use `xprop` To get the name of your polybar.

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.

DEPENDENCIES
------------

polybar
xdotool
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
