#!/bin/bash

NAME="labdraft"
VERSION="0.011"
AUTHOR="budRich"
CONTACT='robstenklippa@gmail.com'
CREATED="2017-11-27"
UPDATED="2017-12-17"

FLD_DRFT="$HOME/www/content/drafts"

main(){
  while getopts :vh option; do
    case "${option}" in
      v) printf '%s\n' \
           "$NAME - version: $VERSION" \
           "updated: $UPDATED by $AUTHOR"
         exit ;;
      h|*) printinfo && exit ;;
    esac
  done

  for f in ${FLD_DRFT}/*; do
    sts=($(awk -F':' '
      $1=="draft"{$2=$2;print $2}
      $1=="target"{$2=$2;print $2;exit}' "$f"))
    if [[ ${sts[0]} = false ]]; then
      found=${f##*/} found=${found%.*}
      trg=${f/drafts/${sts[1]}}
      sta=${f/content/static} sta=${sta%.*}
      mv "$f" "$trg" 
      mv "${sta}" "${sta/drafts/${sts[1]}}"

      echo "$f" "$trg" 
      echo "${sta}" "${sta/drafts/${sts[1]}}"

    fi
  done
}

printinfo(){
  case "$1" in
    m ) printf '%s' "${about}" ;;
    
    f ) 
      printf '%s' "${bouthead}"
      printf '%s' "${about}"
      printf '%s' "${boutfoot}"
    ;;

    ''|* ) 
      printf '%s' "${about}" | awk '
         BEGIN{ind=0}
         $0~/^```/{
           if(ind!="1"){ind="1"}
           else{ind="0"}
           print ""
         }
         $0!~/^```/{
           gsub("[`*]","",$0)
           if(ind=="1"){$0="   " $0}
           print $0
         }
       '
    ;;
  esac
}

bouthead="
${NAME^^} 1 ${CREATED} Linux \"User Manuals\"
=======================================

NAME
----
"

boutfoot="
AUTHOR
------

${AUTHOR} <${CONTACT}>
<https://budrich.github.io>
"

about='
`undraft` - Undraft files on site

SYNOPSIS
--------

`undraft` [`-v`|`-h`]

DESCRIPTION
-----------

Moves draft articles in the drafts folder to
the location specified with the yaml key *target*.
And un-draft the article(s).

OPTIONS
-------

`-v`
  Show version and exit.

`-h`
  Show help and exit.
'

if [ "$1" = "md" ]; then
  printinfo m
  exit
elif [ "$1" = "man" ]; then
  printinfo f
  exit
else
  main "${@}"
fi
